/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE1006  // parts of the code use IDL spelling

namespace GameObject
{

  public partial class Item : TBase
  {
    private long _uid;
    private long _itemId;
    private int _count;

    public long Uid
    {
      get
      {
        return _uid;
      }
      set
      {
        __isset.uid = true;
        this._uid = value;
      }
    }

    public long ItemId
    {
      get
      {
        return _itemId;
      }
      set
      {
        __isset.itemId = true;
        this._itemId = value;
      }
    }

    public int Count
    {
      get
      {
        return _count;
      }
      set
      {
        __isset.count = true;
        this._count = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool uid;
      public bool itemId;
      public bool count;
    }

    public Item()
    {
    }

    public Item DeepCopy()
    {
      var tmp0 = new Item();
      if(__isset.uid)
      {
        tmp0.Uid = this.Uid;
      }
      tmp0.__isset.uid = this.__isset.uid;
      if(__isset.itemId)
      {
        tmp0.ItemId = this.ItemId;
      }
      tmp0.__isset.itemId = this.__isset.itemId;
      if(__isset.count)
      {
        tmp0.Count = this.Count;
      }
      tmp0.__isset.count = this.__isset.count;
      return tmp0;
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I64)
              {
                Uid = await iprot.ReadI64Async(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.I64)
              {
                ItemId = await iprot.ReadI64Async(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 3:
              if (field.Type == TType.I32)
              {
                Count = await iprot.ReadI32Async(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var struc = new TStruct("Item");
        await oprot.WriteStructBeginAsync(struc, cancellationToken);
        var field = new TField();
        if(__isset.uid)
        {
          field.Name = "uid";
          field.Type = TType.I64;
          field.ID = 1;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await oprot.WriteI64Async(Uid, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if(__isset.itemId)
        {
          field.Name = "itemId";
          field.Type = TType.I64;
          field.ID = 2;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await oprot.WriteI64Async(ItemId, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if(__isset.count)
        {
          field.Name = "count";
          field.Type = TType.I32;
          field.ID = 3;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await oprot.WriteI32Async(Count, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object that)
    {
      if (!(that is Item other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return ((__isset.uid == other.__isset.uid) && ((!__isset.uid) || (System.Object.Equals(Uid, other.Uid))))
        && ((__isset.itemId == other.__isset.itemId) && ((!__isset.itemId) || (System.Object.Equals(ItemId, other.ItemId))))
        && ((__isset.count == other.__isset.count) && ((!__isset.count) || (System.Object.Equals(Count, other.Count))));
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if(__isset.uid)
        {
          hashcode = (hashcode * 397) + Uid.GetHashCode();
        }
        if(__isset.itemId)
        {
          hashcode = (hashcode * 397) + ItemId.GetHashCode();
        }
        if(__isset.count)
        {
          hashcode = (hashcode * 397) + Count.GetHashCode();
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var sb = new StringBuilder("Item(");
      int tmp1 = 0;
      if(__isset.uid)
      {
        if(0 < tmp1++) { sb.Append(", "); }
        sb.Append("Uid: ");
        Uid.ToString(sb);
      }
      if(__isset.itemId)
      {
        if(0 < tmp1++) { sb.Append(", "); }
        sb.Append("ItemId: ");
        ItemId.ToString(sb);
      }
      if(__isset.count)
      {
        if(0 < tmp1++) { sb.Append(", "); }
        sb.Append("Count: ");
        Count.ToString(sb);
      }
      sb.Append(')');
      return sb.ToString();
    }
  }

}
